ML for Robotics Lab-3

Example 1: Categorical Data ( Frequency Based)

In [19]:
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
X = pd.DataFrame({'Outlook': ['Sunny','Sunny','Overcast','Rainy','Rainy','Sunny'],
'Humidity': ['High','High','High','Normal','Normal','Normal'], 'Wind': ['Weak','Strong','Weak','Weak','Strong','Weak']})
y = ['No','No','Yes','Yes','No','Yes']
X_encoded1 = X.apply(lambda col:col.astype('category').cat.codes)
model = CategoricalNB()
model.fit(X_encoded1, y)
test = pd.DataFrame([['Sunny','High','Weak']], columns=X.columns)
test_encoded = test.apply(lambda col:col.astype('category').cat.codes)
print(model.predict(test_encoded))

['No']


Example 2: Encoding with OrdinalEncoder

In [20]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
import numpy as np
from sklearn.naive_bayes import CategoricalNB
encoder = OrdinalEncoder()
X_encoded2 = encoder.fit_transform(X)
model = CategoricalNB()
model.fit(X_encoded1, y)
test = pd.DataFrame([['Sunny','High','Weak']], columns=X.columns)
test_encoded = test.apply(lambda col:col.astype('category').cat.codes)
print(model.predict(test_encoded))
y_pred = model.predict(X_encoded1)
print("\nPredicted values:", y_pred)
new_data = pd.DataFrame([['Rainy', 'Normal', 'Strong']], columns=X.columns)
new_x_encoded = new_data.apply(lambda col: col.astype('category').cat.codes)
new_y = model.predict(new_x_encoded)
print(f"\nPrediction for new_data: {new_y[0]}")

['No']

Predicted values: ['No' 'No' 'Yes' 'Yes' 'No' 'Yes']

Prediction for new_data: No


Example 3: Ordinal Encoder Features – Map seen categories

In [21]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
X = pd.DataFrame({'Color': ['Red', 'Blue', 'Green', 'Blue','Red'],
 'Size': ['Small', 'Medium', 'Large','Small', 'Large']
})
y = ['Yes', 'No', 'Yes', 'No', 'Yes']
encoder = OrdinalEncoder()
X_encoded = encoder.fit_transform(X)
print("Encoded Features:\n", X_encoded)
X_test = pd.DataFrame({
 'Color': ['Green', 'Red'],
 'Size': ['Medium', 'Small']
})
X_test_encoded = encoder.transform(X_test)
print("Test Encoded Features:\n", X_test_encoded)

Encoded Features:
 [[2. 2.]
 [0. 1.]
 [1. 0.]
 [0. 2.]
 [2. 0.]]
Test Encoded Features:
 [[1. 1.]
 [2. 2.]]


Example 3: Test data with unseen categories

In [22]:
X_test_new = pd.DataFrame({'Color': ['Yellow'], 'Size': ['Small']})
encoder = OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit(X)
X_test_new_encoded = encoder.transform(X_test_new)
print(X_test_new_encoded)

[[-1.  2.]]


Example 4: Numerical (data) Naïve Bayes (Gaussian Based)

In [23]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
X = np.array([[5.1],[4.9],[5.0],[6.7],[6.5],[6.8]])
y = np.array(['A','A','A','B','B','B'])
model = GaussianNB()
model.fit(X, y)
test = np.array([[5.1]])
print(model.predict(test))

['A']


Example 4: Numerical (data) Naïve Bayes (Gaussian Based)

In [25]:
import pandas as pd
data = {
 'Age': [25, 40, 35, 50, 28],
 'Income': [50000, 60000, 58000, 80000, 52000],
 'MaritalStatus': ['Single', 'Married', 'Single', 'Married','Single'],
 'CreditScore': [700, 650, 720, 600, 690],
 'LoanApproved': ['Yes', 'No', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)
print(df)
X = df.drop('LoanApproved', axis=1)
y = df['LoanApproved']
from sklearn.preprocessing import OrdinalEncoder
categorical_cols = ['MaritalStatus']
encoder = OrdinalEncoder()
X[categorical_cols] = encoder.fit_transform(X[categorical_cols])
print(X)
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, y)
test = pd.DataFrame({
 'Age': [30],
 'Income': [54000],
 'MaritalStatus': ['Single'],
 'CreditScore': [710]
})
test[categorical_cols] = encoder.transform(test[categorical_cols])
pred = model.predict(test)
print("Predicted Loan Approval:", pred[0])

   Age  Income MaritalStatus  CreditScore LoanApproved
0   25   50000        Single          700          Yes
1   40   60000       Married          650           No
2   35   58000        Single          720          Yes
3   50   80000       Married          600           No
4   28   52000        Single          690          Yes
   Age  Income  MaritalStatus  CreditScore
0   25   50000            1.0          700
1   40   60000            0.0          650
2   35   58000            1.0          720
3   50   80000            0.0          600
4   28   52000            1.0          690
Predicted Loan Approval: Yes
